### ISSUE TITLE
IE - Expected Identifier in controller.js

### ISSUE THREAD

**Issue by nddeluca** [centresource/angularjs_rails_demo#1]
An error is thrown in IE due to this line:

 $xhr.defaults.headers.delete['X-CSRF-Token'] = token;

I believe it's due to delete being a keyword - is there a way around this?  The issue causes the example not to work in IE.

**Comment by daniel-nelson** [comment]
Thank you for reporting this issue. I asked on the AngularJS Google group, and Igor suggested the change in the above commit. Please give it a try and let me know if it works. Thanks!

**Comment by daniel-nelson** [comment]
Also, Igor would like to know what version of IE this was happening in. If you would add that here, that would be great. 

Thank you!

**Comment by nddeluca** [comment]
Using ['delete'] instead of .delete solved the issue, thanks!  And this was in IE 8 - both normal and compatibility view.
