### ISSUE TITLE
The vimeo videos are private

### ISSUE THREAD

**Issue by cafedelamar** [centresource/angularjs_rails_demo#8]
The linked vimeo videos seem to be private and not viewable.

Part I gives some background about why we need a javascript framework in the first place.
Part 2 dives into this demo application, including detailed explanation of Angular.js controllers, resources, and templates, as well as where the files reside in the Rails 3.1 file hierarchy.

**Comment by dcalhoun** [comment]
The linked videos had been mistakenly marked as private. They should be viewable now. Sorry for the confusion.
